### ISSUE TITLE
Missing Semi Colon in init() recipes 

### ISSUE THREAD

**Issue by chsWeb** [ak--47/mpEZTrack#18]
**The default implementation code has a semi colon at that end, as follows:**

```
<script src="https://mpeztrack.com/v1.0.0/eztrack.min.js" type="text/javascript"></script>
<script>
mpEZTrack.init("YOUR-PROJECT-TOKEN");
</script>
```
**The code in the init() recipes section is as follows**
`mpEZTrack.init('YOUR-PROJECT-TOKEN', {youtube: true, buttons: false, profiles: false})`

**The recipes also need the ending semicolon, right? Like this:**
```
<script src="https://mpeztrack.com/v1.0.0/eztrack.min.js" type="text/javascript"></script>
<script>
mpEZTrack.init('YOUR-PROJECT-TOKEN', {youtube: true, buttons: false, profiles: false});
</script>
```
I've implemented with the ending semi colon, but I am not getting and events from EZ Track in my project. Might be a cache issue for me, but might be the semi colon missing or not being required?

**Comment by ak--47** [comment]
@chsWeb thanks for the note!

ASI ([automatic semicolon insertion](https://stackoverflow.com/questions/2846283/what-are-the-rules-for-javascripts-automatic-semicolon-insertion-asi)) is a whole thing in javascript. don't read too much about it, it will make your head turn.

in this particular case, since `mpEZTrack` is by itself between `<script></script>` tags, the semicolon is optional, as it will be automatically inserted by the javascript engine.

if you're not seeing events in your mixpanel project, there may be another issue (like an adblocker, or other js errors)... do you see any errors in your console? did you try [turning on `debug` mode](https://github.com/ak--47/mpEZTrack#:~:text=debug,in%20debug%20mode)?

if you send me a link to your website, i will take a look. thanks!

**Comment by chsWeb** [comment]
The issue has been resolved. I tried a few more things to fix the issue, and one of them fixed it. Thank you for the response and quick explainer.
